diff a/arch/arm/mach-omap2/Makefile b/arch/arm/mach-omap2/Makefile	(rejected hunks)
@@ -331,4 +331,5 @@ obj-$(CONFIG_OMAP_HSI_DEVICE)		+= omap_hsi.o
 obj-$(CONFIG_SEC_MODEM)			+= board-tuna-modems.o
 obj-$(CONFIG_ARCH_OMAP4)		+= omap_dmm.o
 obj-$(CONFIG_OMAP_FIQ_DEBUGGER)		+= omap_fiq_debugger.o
+obj-$(CONFIG_RQ_STATS)			+= rq_stats.o
 
